server:
  port: 13402

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/auth
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

rsa:
  public-key: classpath:certs/public.pem
  private-key: classpath:certs/private.pem
