version: "3.8"

services:
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    restart: on-failure
    ports:
      - "8080:8080"
    image: api-gateway:latest

  auth-service:
    build: ./auth-service
    container_name: auth-service
    restart: on-failure
    ports:
      - "13402:13402"
#    environment:
#      DB_URL: jdbc:postgresql://postgres/auth
    image: auth-service:latest

  measurement-get-service:
    build: ./measurement-get-service
    container_name: measurement-get-service
    restart: on-failure
    ports:
      - "13404:13404"
    environment:
      DB_URL: mongodb://mongo/weather
    image: measurement-get-service:latest

  measurement-post-service:
    build: ./measurement-post-service
    container_name: measurement-post-service
    restart: on-failure
    ports:
      - "13403:13403"
    environment:
      DB_URL: mongodb//mongo/weather
    image: measurement-post-service:latest

  projects-service:
    build: ./projects-service
    container_name: projects-service
    restart: on-failure
    ports:
      - "13401:13401"
    environment:
      DB_URL: mongodb://mongo/weather
    image: projects-service:latest

  mongo:
    image: mongo:6.0.5
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ./docker-volumes/mongo/data:/data/db

  postgres:
    image: postgres:15.3
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth
    volumes:
      - ./docker-volumes/postgres/data:/var/lib/postgresql/data
