eureka:
  client:
    service-url:
      defaultZone: http://service-registry:19990/eureka
  instance:
    prefer-ip-address: true

rsa:
  public-key: classpath:certs/public.pem
  private-key: classpath:certs/private.pem
