#spring:
#  application:
#    name: api-gateway
#  cloud:
#    gateway:
#      default-filters:
#        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: "http://localhost:3000,http://172.20.40.211:3000"
#            allowedHeaders: "*"
#            allowedMethods:
#              - GET
#              - POST
#              - PATCH
#              - DELETE

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:19990/eureka
  instance:
    prefer-ip-address: true

rsa:
  public-key: classpath:certs/public.pem
  private-key: classpath:certs/private.pem
