CREATE SEQUENCE IF NOT EXISTS wfiis.user_seq
INCREMENT 1
START 1;

CREATE SEQUENCE IF NOT EXISTS wfiis.role_seq
INCREMENT 1
START 1;

CREATE SEQUENCE IF NOT EXISTS wfiis.privilege_seq
INCREMENT 1
START 1;

CREATE SEQUENCE IF NOT EXISTS wfiis.project_seq
INCREMENT 1
START 1;