@startuml
component "Client App" as app
component "Projects Service" as projects
component " Measurement\n  GET Service" as measurementGet
component " Measurement\n  POST Service" as measurementPost
component "Auth Service" as auth
component "\tAPI Gateway\t" as gateway
database " Projects\nMongoDB" as projectsDB
database "      Auth\nPostgreSQL" as authDB
database "Measurement\n   MongoDB" as measurementDB

app-d->HTTP
gateway-l-HTTP
projects-d->projectsDB
auth-d->authDB
measurementGet-d->measurementDB
measurementPost-d->measurementDB
gateway-->projects
gateway-d->measurementGet
gateway-d->measurementPost
gateway-r->auth

@enduml