@startuml
component "Client App" as app
component "Sensor Service" as sensors
component "Auth Service" as auth
component "\tAPI Gateway\t" as gateway
database " Project, Measurement\n          MongoDB" as sensorsDB
database "      Auth\nPostgreSQL" as authDB

app-d->HTTP
gateway-l-HTTP
sensors-d->sensorsDB
auth-d->authDB
gateway-r->auth
gateway-d->sensors

@enduml